# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  dockerId: fboucher  
  imageName: myclippings-parser  

steps:

- script: |
    docker build --rm -target tester -t $(dockerId)/$(imageName):v1 .
  displayName: 'Docker Build Tests $(buildConfiguration)'

- script: |
    mkdir TestResults
    docker run --rm -v "$(pwd)/TestResults:/src/MyClipping-Parser.Tests/TestResults" $(dockerId)/$(imageName):v1 
  displayName: 'Docker Run Tests $(buildConfiguration)'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
  displayName: 'Publish Test Results'

- script: |
    docker build --rm -target final -t $(dockerId)/$(imageName):v1 .
  displayName: 'Docker Build Final $(buildConfiguration)'

- script: |
    docker login -u $(dockerId) -p $(dockerPassword)
    docker push $(dockerId)/$(imageName):v1
  displayName: 'Docker Push $(buildConfiguration)'
